chore: test

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 while read local_ref local_sha remote_ref remote_sha; do
     echo "local_ref: $local_ref"
@@ -13,10 +13,10 @@ while read local_ref local_sha remote_ref remote_sha; do
     if [[ "$remote_ref" =~ refs/tags/ ]]; then
         TAG_NAME=${remote_ref#refs/tags/}
 
-        if [[ "$current_branch" != "main" ]]; then
-            echo "Error: You can only push to main branch"
-            exit 1
-        fi
+        # if [[ "$current_branch" != "main" ]]; then
+        #     echo "Error: You can only push to main branch"
+        #     exit 1
+        # fi
 
         if [[ ! "$TAG_NAME" =~ ^v[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]{4}(-(staging|sandbox))?$ ]]; then
             echo "Error: tag name format is incorrect.\nTags must follow the pattern vYYYY.MM.DD.HHmm, vYYYY.MM.DD.HHmm-staging, or vYYYY.MM.DD.HHmm-sandbox\nUse 'npm run tag:create:production', 'npm run tag:create:staging', or 'npm run tag:create:sandbox' for convenient" 
